### PR TITLE
Fixes bug with null values for session key arg in Referer class constructor

### LINKED ISSUE #27: Error: Argument 1 passed to Spatie\Referer\Referer::__construct() must be of the type string, null given
```
Symfony\Component\Debug\Exception\FatalThrowableError
Argument 1 passed to Spatie\Referer\Referer::__construct() must be of the type string, null given
```
Triggered by a request from Amazon-Route53-Health-Check-Service. Looks like sometimes Laravel 6.18 passes in a null sessionKey.

### PR DESCRIPTION
**Pull request by dmyers**
Fixes #27

### CODE REVIEW

**Comment by freekmurze** [comment]
It seems like this breaks the tests on P7.4 - L6.*   

Could you take a look at that?

**Comment by dmyers** [comment]
That was a fast response. =)

I took a look, but I'm not sure of the cause yet, but I did notice it happened on previous commits such as this one right before it on the branch:

https://github.com/spatie/laravel-referer/runs/713136252

**Comment by dmyers** [comment]
@freekmurze what do you think?

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
