### PR TITLE
Update PHP versions

### PR DESCRIPTION
**Pull request by Bouhnosaure**
This pull request solves #35

### CODE REVIEW

**Comment by freekmurze** [comment]
Please make sure the tests run on PHP 8 as well.

**Comment by Bouhnosaure** [comment]
It seems that Laravel 5.8.0 does not support the next major version of PHP and the `fail-fast: true` prevents the test to be executed, have you an idea in order to solve this issue ?

**Comment by freekmurze** [comment]
Let's just drop support for PHP 5.8 👍

**Comment by Bouhnosaure** [comment]
Alright then, i'm on it !

**Comment by Bouhnosaure** [comment]
Windows builds are failing but linux ones are fine

**Comment by freekmurze** [comment]
I'll take care of this. Thanks!

**Comment by Bouhnosaure** [comment]
Allright, thanks and have a nice day !

**Pull request merged**
